import { boolean, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const forbisMembers = pgTable('forbis_members', {
  id: uuid('id').primaryKey().defaultRandom(),
  forbisMemberId: text('forbis_member_id'),
  name: text('name').notNull(),
  email: text('email'),
  phone: text('phone'),
  whatsapp: text('whatsapp'),
  isKmiAlumni: boolean('is_kmi_alumni').default(false),
  kmiYear: text('kmi_year'),
  companyName: text('company_name'),
  boothName: text('booth_name'),
  requestedBoothCategorySlug: text('requested_booth_category_slug'),
  companyDescription: text('company_description'),
  companyPhone: text('company_phone'),
  companyWhatsapp: text('company_whatsapp'),
  companyAddress: text('company_address'),
  companyProvinceCode: text('company_province_code'),
  companyProvinceName: text('company_province_name'),
  companyRegencyCode: text('company_regency_code'),
  companyRegencyName: text('company_regency_name'),
  companyDistrictCode: text('company_district_code'),
  companyDistrictName: text('company_district_name'),
  companyVillageCode: text('company_village_code'),
  companyVillageName: text('company_village_name'),
  legalEntity: text('legal_entity'),
  businessCategory: text('business_category'),
  businessSector: text('business_sector'),
  brandName: text('brand_name'),
  productTags: text('product_tags').array(),
  partnershipConcepts: text('partnership_concepts').array(),
  importKey: text('import_key'),
  importBatchId: text('import_batch_id'),
  sourceFileName: text('source_file_name'),
  rawPayload: jsonb('raw_payload'),
  isActive: boolean('is_active').default(true).notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
